In [83]:
import pymongo
import pandas as pd
myclient = pymongo.MongoClient()    
myCollection = myclient.python_db.samples
#for displaying the raw data from mongo db
# for doc in myCollection.find():
#     print(doc)
#displaying the raw data in dataframe
pd.DataFrame(list(myCollection.find()))

,_id,userId,id,title,body,createdAt,updatedAt,__v
0,61158173df27964778fe5e53,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...,2021-08-12 20:15:47.792,2021-08-12 20:15:47.792,0
1,61158173df27964778fe5e55,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...,2021-08-12 20:15:47.792,2021-08-12 20:15:47.792,0
2,61158173df27964778fe5e54,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...,2021-08-12 20:15:47.792,2021-08-12 20:15:47.792,0
3,61158173df27964778fe5e57,1,6,dolorem eum magni eos aperiam quia,ut aspernatur corporis harum nihil quis provid...,2021-08-12 20:15:47.793,2021-08-12 20:15:47.793,0
4,61158173df27964778fe5e5b,1,10,optio molestias id quia eum,quo et expedita modi cum officia vel magni\ndo...,2021-08-12 20:15:47.793,2021-08-12 20:15:47.793,0
...,...,...,...,...,...,...,...,...
95,61158173df27964778fe5eb1,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...,2021-08-12 20:15:47.796,2021-08-12 20:15:47.796,0
96,61158173df27964778fe5eb2,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...,2021-08-12 20:15:47.796,2021-08-12 20:15:47.796,0
97,61158173df27964778fe5eb3,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...,2021-08-12 20:15:47.796,2021-08-12 20:15:47.796,0
98,61158173df27964778fe5eb4,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...,2021-08-12 20:15:47.796,2021-08-12 20:15:47.796,0
99,61158173df27964778fe5eb5,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...,2021-08-12 20:15:47.796,2021-08-12 20:15:47.796,0

In [102]:
#get sample data from db
getSampleData = pd.DataFrame(list(myCollection.find()))
#save those data frame data to csv
getSampleData.to_csv('saveSampleData.csv', encoding='utf-8')

In [101]:
#reading that newly created csv file via panda
pd.read_csv('saveSampleData.csv')

In [38]:
#create another extra column apart from existing data set and via python code only and in that column
#generate 100 random data
#my column name is "new_column_added" and over there I just multiplied 2 with the id value from DB
df = pd.DataFrame(list(myCollection.find()))
df['new_column_added'] = df['id'] * 2
df[['_id', 'userId', 'id', 'new_column_added', 'title', 'body', 'createdAt', 'updatedAt', '__v']].head(100)

,_id,userId,id,new_column_added,title,body,createdAt,updatedAt,__v
0,61158173df27964778fe5e53,1,2,4,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...,2021-08-12 20:15:47.792,2021-08-12 20:15:47.792,0
1,61158173df27964778fe5e55,1,4,8,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...,2021-08-12 20:15:47.792,2021-08-12 20:15:47.792,0
2,61158173df27964778fe5e54,1,3,6,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...,2021-08-12 20:15:47.792,2021-08-12 20:15:47.792,0
3,61158173df27964778fe5e57,1,6,12,dolorem eum magni eos aperiam quia,ut aspernatur corporis harum nihil quis provid...,2021-08-12 20:15:47.793,2021-08-12 20:15:47.793,0
4,61158173df27964778fe5e5b,1,10,20,optio molestias id quia eum,quo et expedita modi cum officia vel magni\ndo...,2021-08-12 20:15:47.793,2021-08-12 20:15:47.793,0
...,...,...,...,...,...,...,...,...,...
95,61158173df27964778fe5eb1,10,96,192,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...,2021-08-12 20:15:47.796,2021-08-12 20:15:47.796,0
96,61158173df27964778fe5eb2,10,97,194,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...,2021-08-12 20:15:47.796,2021-08-12 20:15:47.796,0
97,61158173df27964778fe5eb3,10,98,196,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...,2021-08-12 20:15:47.796,2021-08-12 20:15:47.796,0
98,61158173df27964778fe5eb4,10,99,198,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...,2021-08-12 20:15:47.796,2021-08-12 20:15:47.796,0
99,61158173df27964778fe5eb5,10,100,200,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...,2021-08-12 20:15:47.796,2021-08-12 20:15:47.796,0

In [45]:
#print top 5 rows
df = pd.DataFrame(list(myCollection.find()))
df['new_column_added'] = df['id'] * 2
df[['_id', 'userId', 'id', 'new_column_added', 'title', 'body', 'createdAt', 'updatedAt', '__v']].head()

,_id,userId,id,new_column_added,title,body,createdAt,updatedAt,__v
0,61158173df27964778fe5e53,1,2,4,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...,2021-08-12 20:15:47.792,2021-08-12 20:15:47.792,0
1,61158173df27964778fe5e55,1,4,8,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...,2021-08-12 20:15:47.792,2021-08-12 20:15:47.792,0
2,61158173df27964778fe5e54,1,3,6,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...,2021-08-12 20:15:47.792,2021-08-12 20:15:47.792,0
3,61158173df27964778fe5e57,1,6,12,dolorem eum magni eos aperiam quia,ut aspernatur corporis harum nihil quis provid...,2021-08-12 20:15:47.793,2021-08-12 20:15:47.793,0
4,61158173df27964778fe5e5b,1,10,20,optio molestias id quia eum,quo et expedita modi cum officia vel magni\ndo...,2021-08-12 20:15:47.793,2021-08-12 20:15:47.793,0

In [47]:
#print what dimensional matrix this dataframe
df = pd.DataFrame(list(myCollection.find()))
df['new_column_added'] = df['id'] * 2
df[['_id', 'userId', 'id', 'new_column_added', 'title', 'body', 'createdAt', 'updatedAt', '__v']].head()
df.ndim

2

In [49]:
#Transpose the above dataframe
df = pd.DataFrame(list(myCollection.find()))
df['new_column_added'] = df['id'] * 2
df[['_id', 'userId', 'id', 'new_column_added', 'title', 'body', 'createdAt', 'updatedAt', '__v']].head()
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
_id,61158173df27964778fe5e53,61158173df27964778fe5e55,61158173df27964778fe5e54,61158173df27964778fe5e57,61158173df27964778fe5e5b,61158173df27964778fe5e52,61158173df27964778fe5e56,61158173df27964778fe5e58,61158173df27964778fe5e59,61158173df27964778fe5e5a,...,61158173df27964778fe5eac,61158173df27964778fe5ead,61158173df27964778fe5eae,61158173df27964778fe5eaf,61158173df27964778fe5eb0,61158173df27964778fe5eb1,61158173df27964778fe5eb2,61158173df27964778fe5eb3,61158173df27964778fe5eb4,61158173df27964778fe5eb5
userId,1,1,1,1,1,1,1,1,1,1,...,10,10,10,10,10,10,10,10,10,10
id,2,4,3,6,10,1,5,7,8,9,...,91,92,93,94,95,96,97,98,99,100
title,qui est esse,eum et est occaecati,ea molestias quasi exercitationem repellat qui...,dolorem eum magni eos aperiam quia,optio molestias id quia eum,sunt aut facere repellat provident occaecati e...,nesciunt quas odio,magnam facilis autem,dolorem dolore est ipsam,nesciunt iure omnis dolorem tempora et accusan...,...,aut amet sed,ratione ex tenetur perferendis,beatae soluta recusandae,qui qui voluptates illo iste minima,id minus libero illum nam ad officiis,quaerat velit veniam amet cupiditate aut numqu...,quas fugiat ut perspiciatis vero provident,laboriosam dolor voluptates,temporibus sit alias delectus eligendi possimu...,at nam consequatur ea labore ea harum
body,est rerum tempore vitae\nsequi sint nihil repr...,ullam et saepe reiciendis voluptatem adipisci\...,et iusto sed quo iure\nvoluptatem occaecati om...,ut aspernatur corporis harum nihil quis provid...,quo et expedita modi cum officia vel magni\ndo...,quia et suscipit\nsuscipit recusandae consequu...,repudiandae veniam quaerat sunt sed\nalias aut...,dolore placeat quibusdam ea quo vitae\nmagni q...,dignissimos aperiam dolorem qui eum\nfacilis q...,consectetur animi nesciunt iure dolore\nenim q...,...,libero voluptate eveniet aperiam sed\nsunt pla...,aut et excepturi dicta laudantium sint rerum n...,dolorem quibusdam ducimus consequuntur dicta a...,aspernatur expedita soluta quo ab ut similique...,earum voluptatem facere provident blanditiis v...,in non odio excepturi sint eum\nlabore volupta...,eum non blanditiis soluta porro quibusdam volu...,doloremque ex facilis sit sint culpa\nsoluta a...,quo deleniti praesentium dicta non quod\naut e...,cupiditate quo est a modi nesciunt soluta\nips...
createdAt,2021-08-12 20:15:47.792000,2021-08-12 20:15:47.792000,2021-08-12 20:15:47.792000,2021-08-12 20:15:47.793000,2021-08-12 20:15:47.793000,2021-08-12 20:15:47.792000,2021-08-12 20:15:47.792000,2021-08-12 20:15:47.793000,2021-08-12 20:15:47.793000,2021-08-12 20:15:47.793000,...,2021-08-12 20:15:47.796000,2021-08-12 20:15:47.796000,2021-08-12 20:15:47.796000,2021-08-12 20:15:47.796000,2021-08-12 20:15:47.796000,2021-08-12 20:15:47.796000,2021-08-12 20:15:47.796000,2021-08-12 20:15:47.796000,2021-08-12 20:15:47.796000,2021-08-12 20:15:47.796000
updatedAt,2021-08-12 20:15:47.792000,2021-08-12 20:15:47.792000,2021-08-12 20:15:47.792000,2021-08-12 20:15:47.793000,2021-08-12 20:15:47.793000,2021-08-12 20:15:47.792000,2021-08-12 20:15:47.792000,2021-08-12 20:15:47.793000,2021-08-12 20:15:47.793000,2021-08-12 20:15:47.793000,...,2021-08-12 20:15:47.796000,2021-08-12 20:15:47.796000,2021-08-12 20:15:47.796000,2021-08-12 20:15:47.796000,2021-08-12 20:15:47.796000,2021-08-12 20:15:47.796000,2021-08-12 20:15:47.796000,2021-08-12 20:15:47.796000,2021-08-12 20:15:47.796000,2021-08-12 20:15:47.796000
__v,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
new_column_added,4,8,6,12,20,2,10,14,16,18,...,182,184,186,188,190,192,194,196,198,200

In [53]:
#after Transposing print what dimensional matrix this dataframe
df = pd.DataFrame(list(myCollection.find()))
df['new_column_added'] = df['id'] * 2
df[['_id', 'userId', 'id', 'new_column_added', 'title', 'body', 'createdAt', 'updatedAt', '__v']].head()
df.transpose()
df.ndim

2

In [ ]:
#what are the things I have learned from this assignment
1. First of all I learned how to use Jupyter Note and how it works. This is awesome !!
2. How to download a set of data in CSV file and Read from a CSV file.
3. Got a little concept of Panda and Numpy and how to use them.
4. Started learning how to write code in Python.
5. Got to know that how to get a dataframe size, shape and dimension as well.
6. What is Transpose and how to to do that in a Dataframe.
and finally last but not the list without your help wont be possible to do that !! Thank you so much big bro !!